export const urls = `http://invitationspace.com
https://www.remove.bg
http://downloadtimecalculator.com
https://www.studyblue.com
https://isthisyour.pw
http://www.stripcreator.com
https://dockerswarm.rocks
http://ghostsingles.com
https://lingojam.com
https://www.burnerapp.com
https://icanhazip.com
https://shutuptrackers.com
https://novoresume.com
https://cvmkr.com
https://accessmars.withgoogle.com
https://www.factoftheday1.com
https://www.freeprivacypolicy.com
https://panopticlick.eff.org
https://lunar.fyi
http://www.windows93.net
http://honestslogans.com
http://make-everything-ok.com
http://gifprint.com
https://studio.stupeflix.com
https://dnschecker.org
https://howsecureismypassword.net
http://notes.io
http://you.regettingold.com
https://rejected.us
http://ffffidget.com
https://minutes.io
https://send.firefox.com
https://www.autoregex.xyz
https://www.sparkpeople.com
https://downdetector.in
https://www.calorieking.com
http://whatthefuckshouldimakefordinner.com
https://textfac.es
http://oswallpapers.com
http://mixlr.com
https://www.mypustak.com
https://vubey.yt
http://goqr.me
https://pitchme.vercel.app
https://www.ecosia.org
http://deadpixelbuddy.com
https://sourcerer.io
http://www.keybr.com
http://seoi.net
http://www.staggeringbeauty.com
https://about.me
https://goproheroes.com
https://builtwith.com
http://www.rap4ever.org
http://all-free-download.com
http://onlineconversion.com
https://www.timeanddate.com
https://seatguru.com
https://quickdraw.withgoogle.com
http://cloudping.bastionhost.org
https://respresso.io
https://www.shellcheck.net
http://titlecase.com
https://www.powerwithindell.game
https://ipinfo.io
https://www.lucidchart.com
https://www.awwwards.com
https://www.pretzel.rocks
https://www.restorephotos.io
https://soombo.com
https://imisstheoffice.eu
http://network-tools.com
https://web.dev
https://guacamole.apache.org
https://www.debugbear.com
https://nohello.net
https://codeclippet.com
https://www.fromlatest.io
http://blahtherapy.com
https://www.preceden.com
https://tunein.com
http://web2pdfconvert.com
http://www.polishmywriting.com
http://radio.garden
http://televisor.com
http://www.whizzpast.com
http://savethesounds.info
https://awesome.re
https://www.mathway.com
https://tls.ulfheim.net
https://fmovies.is
https://faxzero.com
https://www.dbdesigner.net
http://bugmenot.com
https://fast.com
https://neave.com
http://50waystogetajob.com
https://www.freeimages.com
https://www.locabrowser.com
https://api.chucknorris.io
http://www.youtube-mp3.org
http://thistothat.com
https://www.calligrapher.ai
https://webhook.site
http://shinytoylabs.com
https://www.pdfescape.com
https://clickclickclick.click
http://omglasergunspewpewpew.com
https://www.calligraphr.com
https://www.mailinator.com
http://www.boxoh.com
https://htmlmail.pro
https://www.wolframalpha.com
http://www.wordhippo.com
http://www.printwhatyoulike.com
https://egghead.io
https://nightwalk.withgoogle.com
https://gitstalk.netlify.com
https://www.followupthen.com
https://validator.w3.org
https://world-power-plugs.com
https://www.jscreenfix.com
https://study-ccna.com
https://mycvdesigner.com
http://oldcomputers.net
https://asciinema.org
https://www.instructables.com
http://www.twofoods.com
https://www.submarinecablemap.com
http://netflixroulette.net
https://ifttt.com
http://www.patience-is-a-virtue.org
https://bellard.org
https://www.16personalities.com
http://pointerpointer.com
https://getnada.com
https://3dhouseplanner.com
https://alternativeto.net
https://anotepad.com
https://www.sporcle.com
https://theia-ide.org
http://www.zamzar.com
https://www.mindmup.com
https://appear.in
https://fixmie.com
https://camelcamelcamel.com
http://www.online-toolz.com
https://randomstreetview.com
https://pipl.com
http://crossfade.io
https://k8syaml.com
http://www.routerpasswords.com
https://www.feeonlyindia.com
https://en.lichess.org
https://librivox.org
https://www.plustransfer.com
http://www.mapcrunch.com
http://sticker.exchange
http://incompetech.com
http://www.recipepuppy.com
https://explainshell.com
https://www.canva.com
http://www.alertful.com
https://frontendchecklist.io
https://www.windowsremix.com
http://myfridgefood.com
https://theworstwebsiteinthe.world
http://www.freeimages.com
https://www.sumopaint.com
https://regexr.com
https://www.ribbet.com
http://projectsinnetworking.com
https://mxtoolbox.com
http://factsie.com
http://htmlreference.io
https://how-old.net
https://stuvera.com
http://jsbeautifier.org
https://tools.pingdom.com
http://gohighbrow.com
http://iknowwhatyoudownload.com
https://css-tricks.com
http://www.usefulscience.org
http://rhymer.com
http://www.vocalfish.co
http://poolside.fm
https://unsplash.com
https://goalkicker.com
https://nickmakes.website
https://www.etymonline.com
https://www.retailmenot.com
https://www.wordclouds.com
https://www.iconfinder.com
https://haveibeenpwned.com
http://pdf2doc.com
https://www.7cups.com
https://www.charitynavigator.org
https://darkmodelist.com
http://unplugthetv.com
http://whathappenedinmybirthyear.com
https://www.mountainproject.com
https://turnoff.us
https://www.virustotal.com
http://pective.com
https://www.copypastecharacter.com
https://pdfcandy.com
https://www.ixquick.com
https://www.drumeo.com
https://loader.io
https://bundle.js.org
http://www.pdfparser.org
http://map.norsecorp.com
https://www.random.org
http://scr.im
http://recruitahacker.net
https://www.kimovil.com
https://iplocation.io
https://roadtrippers.com
http://internet-map.net
https://codecombat.com
http://www.1happybirthday.com
http://www.didthanoskill.me
https://www.webpagetest.org
https://www.windy.com
https://cidr.online
https://ifconfig.co
https://betterexplained.com
https://theresanaiforthat.com
https://os.directory
http://my90stv.com
http://www.fallingfalling.com
http://noexcuselist.com
https://forvo.com
https://namechk.com
http://motherfuckingwebsite.com
https://homestyler.com
https://www.ifixit.com
https://teuxdeux.com
http://histography.io
http://lang-8.com
http://www.not-secret.com
https://forget.me
http://weirdorconfusing.com
https://gtmetrix.com
http://weavesilk.com
http://zoom.it
https://www.join.me
https://jsonlint.com
https://www.easycron.com
https://freeformatter.com
http://en.akinator.com
http://www.bartleby.com
https://www.mytextarea.com
http://deathdate.info
http://hackertyper.com
https://10minutemail.com
http://www.drawastickman.com
https://www.diffchecker.com
http://www.nothingprivate.ml
https://brokenbear.com
https://dualmonitorbackgrounds.com
https://postale.io
https://alison.com
https://njal.la
https://gethuman.com
https://relax.li
http://protondrive.com
https://everytimezone.com
http://www.iamawesome.com
http://kleki.com
http://www.madehow.com
https://tineye.com
https://www.whoishostingthis.com
https://www.woorank.com
http://megavn.com
https://devlids.com
https://earth.nullschool.net
https://privnote.com
https://gitexplorer.com
https://iplogger.org
http://chapiapp.com
https://aitools.fyi
http://www.getnotify.com
http://shelterpups.com
https://bubbl.us
http://www.essaytyper.com
http://zoomquilt.org
https://www.accountkiller.com
https://tweetfancy.io
https://gitstats.me
https://vectormagic.com
https://learnxinyminutes.com
http://youtube.com
https://ssd.eff.org
https://slackmojis.com
http://www.internetlivestats.com
https://www.kill-the-newsletter.com
https://unlockmybox.com
http://www.csgenerator.com
https://www.visualcv.com
http://cidr.xyz
https://rxresu.me
https://gitcoin.co
http://www.audiocheck.net
https://www.davidc.net
http://jsonresume.io
https://www.spreeder.com
https://www.similarsites.com
https://www.freecycle.org
http://www.commercialtunage.com
https://virusscan.jotti.org
https://amazingnewsletters.com
http://factoclock.com
http://anasomnia.com
https://crontab.guru
http://patatap.com
http://ge.tt
http://www.theuselessweb.com
https://www.draw.io
https://job-ready.herokuapp.com
http://www.oldversion.com
http://www.incredibox.com
https://artillery.io
https://www.futureme.org
https://algorithm-visualizer.org
https://willrobotstakemyjob.com
http://gizoogle.net
https://wetransfer.com
https://stars.chromeexperiments.com
https://ahmia.fi
http://what-is-what.com
http://www.yamllint.com
https://securityplanner.org
https://time.is
https://www.myfonts.com
https://cloudconvert.com
https://howdns.works
https://www.skyscanner.co.in
http://gettingstartedwithchef.com
https://devhints.io
http://wobzip.org
https://www.fiverr.com
http://www.allyoucanread.com
http://typatone.com
https://test-ipv6.com
https://corrupt-a-file.net
https://www.systemrequirementslab.com
https://theringfinders.com
https://www.couchsurfing.com
http://ecomputernotes.com
http://rainymood.com
https://whatisthisthing.vercel.app
https://strobe.cool
http://www.passwordmeter.com
https://thefundoo.com
https://www.topcv.me
http://www.allitebooks.com
https://www.typing.com
https://burnermail.io
https://signature-maker.net
http://www.pointlesssites.com
https://diagramy.com
http://twitternamegenerator.com
https://linuxjourney.com
http://www.factslides.com
https://smallpdf.com
http://www.degraeve.com
https://learngitbranching.js.org
https://maildrop.cc
https://serversforhackers.com
https://send-anywhere.com
https://www.deadmansswitch.net
http://www.stolencamerafinder.com
http://www.urlvoid.com
https://www.howacarworks.com
http://www.freenom.com
http://file-upload.com
https://crontab-generator.org
https://localstack.cloud
http://www.fakenamegenerator.com
https://www.upwork.com
http://www.foxebook.net
http://www.keyboardtester.com
http://www.studentrate.com
https://www.flightradar24.com
https://codebeautify.org
https://validate.puppet.com
http://tedib.com
http://touchpianist.com
http://getintopc.com
https://burner.bonanza.com
https://screenshot.guru
https://www.donkeycar.com
http://www.wordle.net
https://www.onlineocr.net
http://downforeveryoneorjustme.com
https://chirpty.com`
  .split('\n')
  .filter((s) => s.trim().length > 0);
